GET localhost:8080/api/v1/adverts?
    make=Skoda
    &model=Fabia
    &bodyType=City+Car
    &color=Gray
    &fuelType=Petrol
    &transmissionType=Manual
    &drivetrainType=Front-Wheel+Drive
    &doors=4
    &seats=5
    &minYear=2010
    &maxYear=2020
    &minMileage=15000
    &maxMileage=55000
    &minEnginePower=70
    &maxEnginePower=200
    &minEngineCapacity=1100
    &maxEngineCapacity=2500
    &isDamaged=false
    &features=Air+Conditioning
    &features=Power+Windows
    &page=0
    &size=10