PUT http://localhost:8080/api/v1/adverts/1
Content-Type: application/json

{
  "sellerId": 1,
  "title": "Skoda Fabia",
  "description": "Even faster now",
  "locationId": 1,
  "price": 25000,
  "phoneNumbers": [
    "123454321",
    "556677889"
  ],
  "vin": "1HGCM82633A000098",
  "make": "Skoda",
  "model": "Fabia",
  "bodyType": "City Car",
  "color": "Gray",
  "fuelType": "Petrol",
  "transmissionType": "Manual",
  "drivetrainType": "Front-Wheel Drive",
  "doorsCount": 4,
  "seatsCount": 5,
  "productionYear": 2010,
  "mileage": 51000,
  "enginePower": 71,
  "engineCapacity": 1198,
  "isDamaged": false,
  "features": [
    "Air Conditioning",
    "Power Windows"
  ]
}
