POST http://localhost:8080/api/v1/adverts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJURVNUIiwiaWF0IjoxNzExMjg4MTg2LCJleHAiOjE3MTEyOTgyNjZ9.6i4ey8-cNBXpjQeskXZRdqzjECra4lzosCVsyC91-XQ
Content-Length: 593
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.9)
Cookie: JSESSIONID=408216BA0E5DB2BC3B80DA18A72792FD
Accept-Encoding: br,deflate,gzip,x-gzip

{
  "title": "Skoda Fabia",
  "description": "Really cool fast car",
  "locationId": 1,
  "price": 25000,
  "phoneNumbers": [
    "123454321",
    "556677889"
  ],
  "vin": "1HGCM82633A000098",
  "make": "Skoda",
  "model": "Fabia",
  "bodyType": "City Car",
  "color": "Gray",
  "fuelType": "Petrol",
  "transmissionType": "Manual",
  "drivetrainType": "Front-Wheel Drive",
  "doorsCount": 4,
  "seatsCount": 5,
  "productionYear": 2010,
  "mileage": 51000,
  "enginePower": 71,
  "engineCapacity": 1198,
  "isDamaged": false,
  "features": [
    "Air Conditioning",
    "Power Windows"
  ]
}

<> 2024-03-24T154505.201.json

###

POST http://localhost:8080/api/v1/auth/authenticate
Content-Type: application/json
Content-Length: 50
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.9)
Cookie: JSESSIONID=408216BA0E5DB2BC3B80DA18A72792FD
Accept-Encoding: br,deflate,gzip,x-gzip

{
  "username": "TEST",
  "password": "test1234"
}

###

POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json
Content-Length: 113
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.9)
Cookie: JSESSIONID=408216BA0E5DB2BC3B80DA18A72792FD
Accept-Encoding: br,deflate,gzip,x-gzip

{
  "username": "TEST",
  "email": "test@email.com",
  "password": "test1234",
  "matchingPassword": "test1234"
}

<> 2024-03-24T151328.201.json

###

DELETE http://localhost:8080/api/v1/adverts/6
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJURVNUIiwiaWF0IjoxNzExMjg4MTg2LCJleHAiOjE3MTEyOTgyNjZ9.6i4ey8-cNBXpjQeskXZRdqzjECra4lzosCVsyC91-XQ
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.9)
Cookie: JSESSIONID=408216BA0E5DB2BC3B80DA18A72792FD
Accept-Encoding: br,deflate,gzip,x-gzip

###

PUT http://localhost:8080/api/v1/adverts/6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJURVNUIiwiaWF0IjoxNzExMjg4MTg2LCJleHAiOjE3MTEyOTgyNjZ9.6i4ey8-cNBXpjQeskXZRdqzjECra4lzosCVsyC91-XQ
Content-Length: 588
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.9)
Cookie: JSESSIONID=408216BA0E5DB2BC3B80DA18A72792FD
Accept-Encoding: br,deflate,gzip,x-gzip

{
  "title": "Skoda Fabia",
  "description": "Even faster now",
  "locationId": 1,
  "price": 25000,
  "phoneNumbers": [
    "123454321",
    "556677889"
  ],
  "vin": "1HGCM82633A000098",
  "make": "Skoda",
  "model": "Fabia",
  "bodyType": "City Car",
  "color": "Gray",
  "fuelType": "Petrol",
  "transmissionType": "Manual",
  "drivetrainType": "Front-Wheel Drive",
  "doorsCount": 4,
  "seatsCount": 5,
  "productionYear": 2010,
  "mileage": 51000,
  "enginePower": 71,
  "engineCapacity": 1198,
  "isDamaged": false,
  "features": [
    "Air Conditioning",
    "Power Windows"
  ]
}

<> 2024-03-24T150929.200.json

###

PUT http://localhost:8080/api/v1/adverts/5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJURVNUIiwiaWF0IjoxNzExMjg4MTg2LCJleHAiOjE3MTEyOTgyNjZ9.6i4ey8-cNBXpjQeskXZRdqzjECra4lzosCVsyC91-XQ
Content-Length: 588
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.9)
Cookie: JSESSIONID=408216BA0E5DB2BC3B80DA18A72792FD
Accept-Encoding: br,deflate,gzip,x-gzip

{
  "title": "Skoda Fabia",
  "description": "Even faster now",
  "locationId": 1,
  "price": 25000,
  "phoneNumbers": [
    "123454321",
    "556677889"
  ],
  "vin": "1HGCM82633A000098",
  "make": "Skoda",
  "model": "Fabia",
  "bodyType": "City Car",
  "color": "Gray",
  "fuelType": "Petrol",
  "transmissionType": "Manual",
  "drivetrainType": "Front-Wheel Drive",
  "doorsCount": 4,
  "seatsCount": 5,
  "productionYear": 2010,
  "mileage": 51000,
  "enginePower": 71,
  "engineCapacity": 1198,
  "isDamaged": false,
  "features": [
    "Air Conditioning",
    "Power Windows"
  ]
}

<> 2024-03-24T150922.500.json

###

GET http://localhost:8080/api/v1/adverts/6
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.9)
Cookie: JSESSIONID=408216BA0E5DB2BC3B80DA18A72792FD
Accept-Encoding: br,deflate,gzip,x-gzip

<> 2024-03-24T150911.200.json

###

GET http://localhost:8080/api/v1/adverts/5
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.9)
Cookie: JSESSIONID=408216BA0E5DB2BC3B80DA18A72792FD
Accept-Encoding: br,deflate,gzip,x-gzip

<> 2024-03-24T150902.200.json

###

POST http://localhost:8080/api/v1/adverts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJURVNUIiwiaWF0IjoxNzExMjg4MTg2LCJleHAiOjE3MTEyOTgyNjZ9.6i4ey8-cNBXpjQeskXZRdqzjECra4lzosCVsyC91-XQ
Content-Length: 593
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.9)
Cookie: JSESSIONID=408216BA0E5DB2BC3B80DA18A72792FD
Accept-Encoding: br,deflate,gzip,x-gzip

{
  "title": "Skoda Fabia",
  "description": "Really cool fast car",
  "locationId": 1,
  "price": 25000,
  "phoneNumbers": [
    "123454321",
    "556677889"
  ],
  "vin": "1HGCM82633A000098",
  "make": "Skoda",
  "model": "Fabia",
  "bodyType": "City Car",
  "color": "Gray",
  "fuelType": "Petrol",
  "transmissionType": "Manual",
  "drivetrainType": "Front-Wheel Drive",
  "doorsCount": 4,
  "seatsCount": 5,
  "productionYear": 2010,
  "mileage": 51000,
  "enginePower": 71,
  "engineCapacity": 1198,
  "isDamaged": false,
  "features": [
    "Air Conditioning",
    "Power Windows"
  ]
}

<> 2024-03-24T150845.201.json

###

PUT http://localhost:8080/api/v1/adverts/5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJURVNUIiwiaWF0IjoxNzExMjg4MTg2LCJleHAiOjE3MTEyOTgyNjZ9.6i4ey8-cNBXpjQeskXZRdqzjECra4lzosCVsyC91-XQ
Content-Length: 588
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.9)
Cookie: JSESSIONID=408216BA0E5DB2BC3B80DA18A72792FD
Accept-Encoding: br,deflate,gzip,x-gzip

{
  "title": "Skoda Fabia",
  "description": "Even faster now",
  "locationId": 1,
  "price": 25000,
  "phoneNumbers": [
    "123454321",
    "556677889"
  ],
  "vin": "1HGCM82633A000098",
  "make": "Skoda",
  "model": "Fabia",
  "bodyType": "City Car",
  "color": "Gray",
  "fuelType": "Petrol",
  "transmissionType": "Manual",
  "drivetrainType": "Front-Wheel Drive",
  "doorsCount": 4,
  "seatsCount": 5,
  "productionYear": 2010,
  "mileage": 51000,
  "enginePower": 71,
  "engineCapacity": 1198,
  "isDamaged": false,
  "features": [
    "Air Conditioning",
    "Power Windows"
  ]
}

<> 2024-03-24T150823.500.json

###

GET http://localhost:8080/api/v1/adverts/5
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.9)
Cookie: JSESSIONID=408216BA0E5DB2BC3B80DA18A72792FD
Accept-Encoding: br,deflate,gzip,x-gzip

<> 2024-03-24T150812.200.json

###

PUT http://localhost:8080/api/v1/adverts/5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJURVNUIiwiaWF0IjoxNzExMjg4MTg2LCJleHAiOjE3MTEyOTgyNjZ9.6i4ey8-cNBXpjQeskXZRdqzjECra4lzosCVsyC91-XQ
Content-Length: 605
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.9)
Cookie: JSESSIONID=408216BA0E5DB2BC3B80DA18A72792FD
Accept-Encoding: br,deflate,gzip,x-gzip

{
  "sellerId": 5,
  "title": "Skoda Fabia",
  "description": "Even faster now",
  "locationId": 1,
  "price": 25000,
  "phoneNumbers": [
    "123454321",
    "556677889"
  ],
  "vin": "1HGCM82633A000098",
  "make": "Skoda",
  "model": "Fabia",
  "bodyType": "City Car",
  "color": "Gray",
  "fuelType": "Petrol",
  "transmissionType": "Manual",
  "drivetrainType": "Front-Wheel Drive",
  "doorsCount": 4,
  "seatsCount": 5,
  "productionYear": 2010,
  "mileage": 51000,
  "enginePower": 71,
  "engineCapacity": 1198,
  "isDamaged": false,
  "features": [
    "Air Conditioning",
    "Power Windows"
  ]
}

<> 2024-03-24T145507.500.json

###

PUT http://localhost:8080/api/v1/adverts/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJURVNUIiwiaWF0IjoxNzExMjg4MTg2LCJleHAiOjE3MTEyOTgyNjZ9.6i4ey8-cNBXpjQeskXZRdqzjECra4lzosCVsyC91-XQ
Content-Length: 605
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.9)
Cookie: JSESSIONID=408216BA0E5DB2BC3B80DA18A72792FD
Accept-Encoding: br,deflate,gzip,x-gzip

{
  "sellerId": 5,
  "title": "Skoda Fabia",
  "description": "Even faster now",
  "locationId": 1,
  "price": 25000,
  "phoneNumbers": [
    "123454321",
    "556677889"
  ],
  "vin": "1HGCM82633A000098",
  "make": "Skoda",
  "model": "Fabia",
  "bodyType": "City Car",
  "color": "Gray",
  "fuelType": "Petrol",
  "transmissionType": "Manual",
  "drivetrainType": "Front-Wheel Drive",
  "doorsCount": 4,
  "seatsCount": 5,
  "productionYear": 2010,
  "mileage": 51000,
  "enginePower": 71,
  "engineCapacity": 1198,
  "isDamaged": false,
  "features": [
    "Air Conditioning",
    "Power Windows"
  ]
}

<> 2024-03-24T145234.500.json

###

PUT http://localhost:8080/api/v1/adverts/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJURVNUIiwiaWF0IjoxNzExMjg4MTg2LCJleHAiOjE3MTEyOTgyNjZ9.6i4ey8-cNBXpjQeskXZRdqzjECra4lzosCVsyC91-XQ
Content-Length: 605
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.9)
Cookie: JSESSIONID=408216BA0E5DB2BC3B80DA18A72792FD
Accept-Encoding: br,deflate,gzip,x-gzip

{
  "sellerId": 5,
  "title": "Skoda Fabia",
  "description": "Even faster now",
  "locationId": 1,
  "price": 25000,
  "phoneNumbers": [
    "123454321",
    "556677889"
  ],
  "vin": "1HGCM82633A000098",
  "make": "Skoda",
  "model": "Fabia",
  "bodyType": "City Car",
  "color": "Gray",
  "fuelType": "Petrol",
  "transmissionType": "Manual",
  "drivetrainType": "Front-Wheel Drive",
  "doorsCount": 4,
  "seatsCount": 5,
  "productionYear": 2010,
  "mileage": 51000,
  "enginePower": 71,
  "engineCapacity": 1198,
  "isDamaged": false,
  "features": [
    "Air Conditioning",
    "Power Windows"
  ]
}

<> 2024-03-24T145158.500.json

###

PUT http://localhost:8080/api/v1/adverts/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJURVNUIiwiaWF0IjoxNzExMjg4MTg2LCJleHAiOjE3MTEyOTgyNjZ9.6i4ey8-cNBXpjQeskXZRdqzjECra4lzosCVsyC91-XQ
Content-Length: 605
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.9)
Cookie: JSESSIONID=408216BA0E5DB2BC3B80DA18A72792FD
Accept-Encoding: br,deflate,gzip,x-gzip

{
  "sellerId": 5,
  "title": "Skoda Fabia",
  "description": "Even faster now",
  "locationId": 1,
  "price": 25000,
  "phoneNumbers": [
    "123454321",
    "556677889"
  ],
  "vin": "1HGCM82633A000098",
  "make": "Skoda",
  "model": "Fabia",
  "bodyType": "City Car",
  "color": "Gray",
  "fuelType": "Petrol",
  "transmissionType": "Manual",
  "drivetrainType": "Front-Wheel Drive",
  "doorsCount": 4,
  "seatsCount": 5,
  "productionYear": 2010,
  "mileage": 51000,
  "enginePower": 71,
  "engineCapacity": 1198,
  "isDamaged": false,
  "features": [
    "Air Conditioning",
    "Power Windows"
  ]
}

<> 2024-03-24T145109.500.json

###

PUT http://localhost:8080/api/v1/adverts/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJURVNUIiwiaWF0IjoxNzExMjg4MTg2LCJleHAiOjE3MTEyOTgyNjZ9.6i4ey8-cNBXpjQeskXZRdqzjECra4lzosCVsyC91-XQ
Content-Length: 605
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.9)
Cookie: JSESSIONID=408216BA0E5DB2BC3B80DA18A72792FD
Accept-Encoding: br,deflate,gzip,x-gzip

{
  "sellerId": 4,
  "title": "Skoda Fabia",
  "description": "Even faster now",
  "locationId": 1,
  "price": 25000,
  "phoneNumbers": [
    "123454321",
    "556677889"
  ],
  "vin": "1HGCM82633A000098",
  "make": "Skoda",
  "model": "Fabia",
  "bodyType": "City Car",
  "color": "Gray",
  "fuelType": "Petrol",
  "transmissionType": "Manual",
  "drivetrainType": "Front-Wheel Drive",
  "doorsCount": 4,
  "seatsCount": 5,
  "productionYear": 2010,
  "mileage": 51000,
  "enginePower": 71,
  "engineCapacity": 1198,
  "isDamaged": false,
  "features": [
    "Air Conditioning",
    "Power Windows"
  ]
}

<> 2024-03-24T145104.500.json

###

PUT http://localhost:8080/api/v1/adverts/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJURVNUIiwiaWF0IjoxNzExMjg4MTg2LCJleHAiOjE3MTEyOTgyNjZ9.6i4ey8-cNBXpjQeskXZRdqzjECra4lzosCVsyC91-XQ
Content-Length: 605
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.9)
Cookie: JSESSIONID=408216BA0E5DB2BC3B80DA18A72792FD
Accept-Encoding: br,deflate,gzip,x-gzip

{
  "sellerId": 2,
  "title": "Skoda Fabia",
  "description": "Even faster now",
  "locationId": 1,
  "price": 25000,
  "phoneNumbers": [
    "123454321",
    "556677889"
  ],
  "vin": "1HGCM82633A000098",
  "make": "Skoda",
  "model": "Fabia",
  "bodyType": "City Car",
  "color": "Gray",
  "fuelType": "Petrol",
  "transmissionType": "Manual",
  "drivetrainType": "Front-Wheel Drive",
  "doorsCount": 4,
  "seatsCount": 5,
  "productionYear": 2010,
  "mileage": 51000,
  "enginePower": 71,
  "engineCapacity": 1198,
  "isDamaged": false,
  "features": [
    "Air Conditioning",
    "Power Windows"
  ]
}

<> 2024-03-24T145059.500.json

###

POST http://localhost:8080/api/v1/adverts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJURVNUIiwiaWF0IjoxNzExMjg4MTg2LCJleHAiOjE3MTEyOTgyNjZ9.6i4ey8-cNBXpjQeskXZRdqzjECra4lzosCVsyC91-XQ
Content-Length: 610
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.9)
Cookie: JSESSIONID=408216BA0E5DB2BC3B80DA18A72792FD
Accept-Encoding: br,deflate,gzip,x-gzip

{
  "sellerId": 2,
  "title": "Skoda Fabia",
  "description": "Really cool fast car",
  "locationId": 1,
  "price": 25000,
  "phoneNumbers": [
    "123454321",
    "556677889"
  ],
  "vin": "1HGCM82633A000098",
  "make": "Skoda",
  "model": "Fabia",
  "bodyType": "City Car",
  "color": "Gray",
  "fuelType": "Petrol",
  "transmissionType": "Manual",
  "drivetrainType": "Front-Wheel Drive",
  "doorsCount": 4,
  "seatsCount": 5,
  "productionYear": 2010,
  "mileage": 51000,
  "enginePower": 71,
  "engineCapacity": 1198,
  "isDamaged": false,
  "features": [
    "Air Conditioning",
    "Power Windows"
  ]
}

<> 2024-03-24T145004.201.json

###

POST http://localhost:8080/api/v1/auth/authenticate
Content-Type: application/json
Content-Length: 50
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.9)
Cookie: JSESSIONID=408216BA0E5DB2BC3B80DA18A72792FD
Accept-Encoding: br,deflate,gzip,x-gzip

{
  "username": "TEST",
  "password": "test1234"
}

###

POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json
Content-Length: 113
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.9)
Cookie: JSESSIONID=408216BA0E5DB2BC3B80DA18A72792FD
Accept-Encoding: br,deflate,gzip,x-gzip

{
  "username": "TEST",
  "email": "test@email.com",
  "password": "test1234",
  "matchingPassword": "test1234"
}

<> 2024-03-24T144849.201.json

###

POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json
Content-Length: 113
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.9)
Cookie: JSESSIONID=408216BA0E5DB2BC3B80DA18A72792FD
Accept-Encoding: br,deflate,gzip,x-gzip

{
  "username": "TEST",
  "email": "test@email.com",
  "password": "test1234",
  "matchingPassword": "test1234"
}

<> 2024-03-24T144559.500.json

###

POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json
Content-Length: 113
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.9)
Cookie: JSESSIONID=408216BA0E5DB2BC3B80DA18A72792FD
Accept-Encoding: br,deflate,gzip,x-gzip

{
  "username": "TEST",
  "email": "test@email.com",
  "password": "test1234",
  "matchingPassword": "test1234"
}

<> 2024-03-24T144518.500.json

###

POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json
Content-Length: 113
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.9)
Cookie: JSESSIONID=408216BA0E5DB2BC3B80DA18A72792FD
Accept-Encoding: br,deflate,gzip,x-gzip

{
  "username": "TEST",
  "email": "test@email.com",
  "password": "test1234",
  "matchingPassword": "test1234"
}

<> 2024-03-24T144352.500.json

###

POST http://localhost:8080/api/v1/adverts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJURVNUIiwiaWF0IjoxNzExMjg0NTI0LCJleHAiOjE3MTEyOTQ2MDR9.kZoZQMIfCmjUFBk_aZMQ1pq2cYENK3dpe-lv8yAKhLc
Content-Length: 610
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.9)
Cookie: JSESSIONID=408216BA0E5DB2BC3B80DA18A72792FD
Accept-Encoding: br,deflate,gzip,x-gzip

{
  "sellerId": 2,
  "title": "Skoda Fabia",
  "description": "Really cool fast car",
  "locationId": 1,
  "price": 25000,
  "phoneNumbers": [
    "123454321",
    "556677889"
  ],
  "vin": "1HGCM82633A000098",
  "make": "Skoda",
  "model": "Fabia",
  "bodyType": "City Car",
  "color": "Gray",
  "fuelType": "Petrol",
  "transmissionType": "Manual",
  "drivetrainType": "Front-Wheel Drive",
  "doorsCount": 4,
  "seatsCount": 5,
  "productionYear": 2010,
  "mileage": 51000,
  "enginePower": 71,
  "engineCapacity": 1198,
  "isDamaged": false,
  "features": [
    "Air Conditioning",
    "Power Windows"
  ]
}

###

POST http://localhost:8080/api/v1/adverts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJURVNUIiwiaWF0IjoxNzExMjg0NTI0LCJleHAiOjE3MTEyOTQ2MDR9.kZoZQMIfCmjUFBk_aZMQ1pq2cYENK3dpe-lv8yAKhLc
Content-Length: 610
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.9)
Cookie: JSESSIONID=408216BA0E5DB2BC3B80DA18A72792FD
Accept-Encoding: br,deflate,gzip,x-gzip

{
  "sellerId": 2,
  "title": "Skoda Fabia",
  "description": "Really cool fast car",
  "locationId": 1,
  "price": 25000,
  "phoneNumbers": [
    "123454321",
    "556677889"
  ],
  "vin": "1HGCM82633A000098",
  "make": "Skoda",
  "model": "Fabia",
  "bodyType": "City Car",
  "color": "Gray",
  "fuelType": "Petrol",
  "transmissionType": "Manual",
  "drivetrainType": "Front-Wheel Drive",
  "doorsCount": 4,
  "seatsCount": 5,
  "productionYear": 2010,
  "mileage": 51000,
  "enginePower": 71,
  "engineCapacity": 1198,
  "isDamaged": false,
  "features": [
    "Air Conditioning",
    "Power Windows"
  ]
}

<> 2024-03-24T142152.201.json

###

POST http://localhost:8080/api/v1/adverts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJURVNUIiwiaWF0IjoxNzExMjg0NTI0LCJleHAiOjE3MTEyOTQ2MDR9.kZoZQMIfCmjUFBk_aZMQ1pq2cYENK3dpe-lv8yAKhLc
Content-Length: 610
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.9)
Cookie: JSESSIONID=408216BA0E5DB2BC3B80DA18A72792FD
Accept-Encoding: br,deflate,gzip,x-gzip

{
  "sellerId": 2,
  "title": "Skoda Fabia",
  "description": "Really cool fast car",
  "locationId": 1,
  "price": 25000,
  "phoneNumbers": [
    "123454321",
    "556677889"
  ],
  "vin": "1HGCM82633A000098",
  "make": "Skoda",
  "model": "Fabia",
  "bodyType": "City Car",
  "color": "Gray",
  "fuelType": "Petrol",
  "transmissionType": "Manual",
  "drivetrainType": "Front-Wheel Drive",
  "doorsCount": 4,
  "seatsCount": 5,
  "productionYear": 2010,
  "mileage": 51000,
  "enginePower": 71,
  "engineCapacity": 1198,
  "isDamaged": false,
  "features": [
    "Air Conditioning",
    "Power Windows"
  ]
}

<> 2024-03-24T141740.400.json

###

POST http://localhost:8080/api/v1/adverts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiURVNUIiwiaWF0IjoxNzExMjg0NTI0LCJleHAiOjE3MTEyOTQ2MDR9.kZoZQMIfCmjUFBk_aZMQ1pq2cYENK3dpe-lv8yAKhLc
Content-Length: 610
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.9)
Cookie: JSESSIONID=408216BA0E5DB2BC3B80DA18A72792FD
Accept-Encoding: br,deflate,gzip,x-gzip

{
  "sellerId": 2,
  "title": "Skoda Fabia",
  "description": "Really cool fast car",
  "locationId": 1,
  "price": 25000,
  "phoneNumbers": [
    "123454321",
    "556677889"
  ],
  "vin": "1HGCM82633A000098",
  "make": "Skoda",
  "model": "Fabia",
  "bodyType": "City Car",
  "color": "Gray",
  "fuelType": "Petrol",
  "transmissionType": "Manual",
  "drivetrainType": "Front-Wheel Drive",
  "doorsCount": 4,
  "seatsCount": 5,
  "productionYear": 2010,
  "mileage": 51000,
  "enginePower": 71,
  "engineCapacity": 1198,
  "isDamaged": false,
  "features": [
    "Air Conditioning",
    "Power Windows"
  ]
}

###

POST http://localhost:8080/api/v1/adverts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJURVNUIiwiaWF0IjoxNzExMjg0NTI0LCJleHAiOjE3MTEyOTQ2MDR9.kZoZQMIfCmjUFBk_aZMQ1pq2cYENK3dpe-lv8yAKhLc
Content-Length: 610
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.9)
Cookie: JSESSIONID=408216BA0E5DB2BC3B80DA18A72792FD
Accept-Encoding: br,deflate,gzip,x-gzip

{
  "sellerId": 2,
  "title": "Skoda Fabia",
  "description": "Really cool fast car",
  "locationId": 1,
  "price": 25000,
  "phoneNumbers": [
    "123454321",
    "556677889"
  ],
  "vin": "1HGCM82633A000098",
  "make": "Skoda",
  "model": "Fabia",
  "bodyType": "City Car",
  "color": "Gray",
  "fuelType": "Petrol",
  "transmissionType": "Manual",
  "drivetrainType": "Front-Wheel Drive",
  "doorsCount": 4,
  "seatsCount": 5,
  "productionYear": 2010,
  "mileage": 51000,
  "enginePower": 71,
  "engineCapacity": 1198,
  "isDamaged": false,
  "features": [
    "Air Conditioning",
    "Power Windows"
  ]
}

<> 2024-03-24T141709.400.json

###

POST http://localhost:8080/api/v1/adverts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJURVNUIiwiaWF0IjoxNzExMjg0NTI0LCJleHAiOjE3MTEyOTQ2MDR9.kZoZQMIfCmjUFBk_aZMQ1pq2cYENK3dpe-lv8yAKhLc
Content-Length: 610
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.9)
Cookie: JSESSIONID=12F975AD0A6F5AB732469FEC9EA442C2
Accept-Encoding: br,deflate,gzip,x-gzip

{
  "sellerId": 2,
  "title": "Skoda Fabia",
  "description": "Really cool fast car",
  "locationId": 1,
  "price": 25000,
  "phoneNumbers": [
    "123454321",
    "556677889"
  ],
  "vin": "1HGCM82633A000098",
  "make": "Skoda",
  "model": "Fabia",
  "bodyType": "City Car",
  "color": "Gray",
  "fuelType": "Petrol",
  "transmissionType": "Manual",
  "drivetrainType": "Front-Wheel Drive",
  "doorsCount": 4,
  "seatsCount": 5,
  "productionYear": 2010,
  "mileage": 51000,
  "enginePower": 71,
  "engineCapacity": 1198,
  "isDamaged": false,
  "features": [
    "Air Conditioning",
    "Power Windows"
  ]
}

###

POST http://localhost:8080/api/v1/adverts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJURVNUIiwiaWF0IjoxNzExMjg0NTI0LCJleHAiOjE3MTEyOTQ2MDR9.kZoZQMIfCmjUFBk_aZMQ1pq2cYENK3dpe-lv8yAKhLc
Content-Length: 610
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.9)
Cookie: JSESSIONID=12F975AD0A6F5AB732469FEC9EA442C2
Accept-Encoding: br,deflate,gzip,x-gzip

{
  "sellerId": 2,
  "title": "Skoda Fabia",
  "description": "Really cool fast car",
  "locationId": 1,
  "price": 25000,
  "phoneNumbers": [
    "123454321",
    "556677889"
  ],
  "vin": "1HGCM82633A000098",
  "make": "Skoda",
  "model": "Fabia",
  "bodyType": "City Car",
  "color": "Gray",
  "fuelType": "Petrol",
  "transmissionType": "Manual",
  "drivetrainType": "Front-Wheel Drive",
  "doorsCount": 4,
  "seatsCount": 5,
  "productionYear": 2010,
  "mileage": 51000,
  "enginePower": 71,
  "engineCapacity": 1198,
  "isDamaged": false,
  "features": [
    "Air Conditioning",
    "Power Windows"
  ]
}

###

POST http://localhost:8080/api/v1/adverts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJURVNUIiwiaWF0IjoxNzExMjg0NTI0LCJleHAiOjE3MTEyOTQ2MDR9.kZoZQMIfCmjUFBk_aZMQ1pq2cYENK3dpe-lv8yAKhLc
Content-Length: 610
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.9)
Cookie: JSESSIONID=1191EB9DC9F35CF114EE1F5E1577CBDB
Accept-Encoding: br,deflate,gzip,x-gzip

{
  "sellerId": 2,
  "title": "Skoda Fabia",
  "description": "Really cool fast car",
  "locationId": 1,
  "price": 25000,
  "phoneNumbers": [
    "123454321",
    "556677889"
  ],
  "vin": "1HGCM82633A000098",
  "make": "Skoda",
  "model": "Fabia",
  "bodyType": "City Car",
  "color": "Gray",
  "fuelType": "Petrol",
  "transmissionType": "Manual",
  "drivetrainType": "Front-Wheel Drive",
  "doorsCount": 4,
  "seatsCount": 5,
  "productionYear": 2010,
  "mileage": 51000,
  "enginePower": 71,
  "engineCapacity": 1198,
  "isDamaged": false,
  "features": [
    "Air Conditioning",
    "Power Windows"
  ]
}

###

POST http://localhost:8080/api/v1/auth/authenticate
Content-Type: application/json
Content-Length: 50
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.9)
Cookie: JSESSIONID=1191EB9DC9F35CF114EE1F5E1577CBDB
Accept-Encoding: br,deflate,gzip,x-gzip

{
  "username": "TEST",
  "password": "test1234"
}

###

POST http://localhost:8080/api/v1/adverts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJURVNUIiwiaWF0IjoxNzExMjg0NTI0LCJleHAiOjE3MTEyOTQ2MDR9.kZoZQMIfCmjUFBk_aZMQ1pq2cYENK3dpe-lv8yAKhLc
Content-Length: 610
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.9)
Cookie: JSESSIONID=6BA14291FA007481486FFFF4BAF742B4
Accept-Encoding: br,deflate,gzip,x-gzip

{
  "sellerId": 2,
  "title": "Skoda Fabia",
  "description": "Really cool fast car",
  "locationId": 1,
  "price": 25000,
  "phoneNumbers": [
    "123454321",
    "556677889"
  ],
  "vin": "1HGCM82633A000098",
  "make": "Skoda",
  "model": "Fabia",
  "bodyType": "City Car",
  "color": "Gray",
  "fuelType": "Petrol",
  "transmissionType": "Manual",
  "drivetrainType": "Front-Wheel Drive",
  "doorsCount": 4,
  "seatsCount": 5,
  "productionYear": 2010,
  "mileage": 51000,
  "enginePower": 71,
  "engineCapacity": 1198,
  "isDamaged": false,
  "features": [
    "Air Conditioning",
    "Power Windows"
  ]
}

###

POST http://localhost:8080/api/v1/auth/authenticate
Content-Type: application/json
Content-Length: 50
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.9)
Cookie: JSESSIONID=6BA14291FA007481486FFFF4BAF742B4
Accept-Encoding: br,deflate,gzip,x-gzip

{
  "username": "TEST",
  "password": "test1234"
}

###

POST http://localhost:8080/api/v1/auth/authenticate
Content-Type: application/json
Content-Length: 50
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.9)
Cookie: JSESSIONID=6BA14291FA007481486FFFF4BAF742B4
Accept-Encoding: br,deflate,gzip,x-gzip

{
  "username": "TEST",
  "password": "test1234"
}

<> 2024-03-24T134517.500.json

###

POST http://localhost:8080/api/v1/auth/authenticate
Content-Type: application/json
Content-Length: 50
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.9)
Cookie: JSESSIONID=6BA14291FA007481486FFFF4BAF742B4
Accept-Encoding: br,deflate,gzip,x-gzip

{
  "username": "TEST",
  "password": "test1234"
}

<> 2024-03-24T134408.500.json

###

POST http://localhost:8080/api/v1/auth/authenticate
Content-Type: application/json
Content-Length: 50
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.9)
Cookie: JSESSIONID=6BA14291FA007481486FFFF4BAF742B4
Accept-Encoding: br,deflate,gzip,x-gzip

{
  "username": "TEST",
  "password": "test1234"
}

<> 2024-03-24T134402.500.json

###

POST http://localhost:8080/api/v1/auth/authenticate
Content-Type: application/json
Content-Length: 50
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.9)
Cookie: JSESSIONID=6BA14291FA007481486FFFF4BAF742B4
Accept-Encoding: br,deflate,gzip,x-gzip

{
  "username": "TEST",
  "password": "test1234"
}

<> 2024-03-24T133845.500.json

###

POST http://localhost:8080/api/v1/auth/authenticate
Content-Type: application/json
Content-Length: 50
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.9)
Cookie: JSESSIONID=6BA14291FA007481486FFFF4BAF742B4
Accept-Encoding: br,deflate,gzip,x-gzip

{
  "username": "TEST",
  "password": "test1234"
}

<> 2024-03-24T133753.500.json

###

POST http://localhost:8080/api/v1/auth/authenticate
Content-Type: application/json
Content-Length: 50
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.9)
Cookie: JSESSIONID=6BA14291FA007481486FFFF4BAF742B4
Accept-Encoding: br,deflate,gzip,x-gzip

{
  "username": "TEST",
  "password": "test1234"
}

<> 2024-03-24T133412.500.json

###

POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json
Content-Length: 50
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.9)
Cookie: JSESSIONID=6BA14291FA007481486FFFF4BAF742B4
Accept-Encoding: br,deflate,gzip,x-gzip

{
  "username": "TEST",
  "password": "test1234"
}

<> 2024-03-24T133359.500.json

###

POST http://localhost:8080/auth/login
Content-Type: application/json
Content-Length: 50
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.9)
Cookie: JSESSIONID=04F5FDB43328AD35351082E3B7662AB9
Accept-Encoding: br,deflate,gzip,x-gzip

{
  "username": "TEST",
  "password": "test1234"
}

###

GET http://localhost:8080/api/v1/adverts/3
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.9)
Cookie: JSESSIONID=04F5FDB43328AD35351082E3B7662AB9
Accept-Encoding: br,deflate,gzip,x-gzip

<> 2024-03-19T194923.200.json

###

GET http://localhost:8080/api/v1/adverts/2
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.9)
Cookie: JSESSIONID=04F5FDB43328AD35351082E3B7662AB9
Accept-Encoding: br,deflate,gzip,x-gzip

<> 2024-03-19T194916.404.json

###

GET http://localhost:8080/api/v1/adverts/1
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.9)
Cookie: JSESSIONID=04F5FDB43328AD35351082E3B7662AB9
Accept-Encoding: br,deflate,gzip,x-gzip

<> 2024-03-19T194908.404.json

###

POST http://localhost:8080/api/v1/adverts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJURVNUIiwiaWF0IjoxNzEwNjg5NTIwLCJleHAiOjE3MTA3NzU5MjB9.byvMd_dT6Yex-w4ZxN12C2OWY7Lkj6DaYdBV8KJ10umZjPdeout7LxWbdRr6Ja1-hEeB5G2adTYW1c5DhD35Cw
Content-Length: 610
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.9)
Cookie: JSESSIONID=04F5FDB43328AD35351082E3B7662AB9
Accept-Encoding: br,deflate,gzip,x-gzip

{
  "sellerId": 2,
  "title": "Skoda Fabia",
  "description": "Really cool fast car",
  "locationId": 1,
  "price": 25000,
  "phoneNumbers": [
    "123454321",
    "556677889"
  ],
  "vin": "1HGCM82633A000098",
  "make": "Skoda",
  "model": "Fabia",
  "bodyType": "City Car",
  "color": "Gray",
  "fuelType": "Petrol",
  "transmissionType": "Manual",
  "drivetrainType": "Front-Wheel Drive",
  "doorsCount": 4,
  "seatsCount": 5,
  "productionYear": 2010,
  "mileage": 51000,
  "enginePower": 71,
  "engineCapacity": 1198,
  "isDamaged": false,
  "features": [
    "Air Conditioning",
    "Power Windows"
  ]
}

###

POST http://localhost:8080/api/v1/adverts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJURVNUIiwiaWF0IjoxNzEwNjg5NTIwLCJleHAiOjE3MTA3NzU5MjB9.byvMd_dT6Yex-w4ZxN12C2OWY7Lkj6DaYdBV8KJ10umZjPdeout7LxWbdRr6Ja1-hEeB5G2adTYW1c5DhD35Cw
Content-Length: 610
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.9)
Cookie: JSESSIONID=50652D5AA72C4456866924BD7F6FDD72
Accept-Encoding: br,deflate,gzip,x-gzip

{
  "sellerId": 2,
  "title": "Skoda Fabia",
  "description": "Really cool fast car",
  "locationId": 1,
  "price": 25000,
  "phoneNumbers": [
    "123454321",
    "556677889"
  ],
  "vin": "1HGCM82633A000098",
  "make": "Skoda",
  "model": "Fabia",
  "bodyType": "City Car",
  "color": "Gray",
  "fuelType": "Petrol",
  "transmissionType": "Manual",
  "drivetrainType": "Front-Wheel Drive",
  "doorsCount": 4,
  "seatsCount": 5,
  "productionYear": 2010,
  "mileage": 51000,
  "enginePower": 71,
  "engineCapacity": 1198,
  "isDamaged": false,
  "features": [
    "Air Conditioning",
    "Power Windows"
  ]
}

###

POST http://localhost:8080/api/v1/adverts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJURVNUIiwiaWF0IjoxNzEwNjg5NTIwLCJleHAiOjE3MTA3NzU5MjB9.byvMd_dT6Yex-w4ZxN12C2OWY7Lkj6DaYdBV8KJ10umZjPdeout7LxWbdRr6Ja1-hEeB5G2adTYW1c5DhD35Cw
Content-Length: 610
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.9)
Cookie: JSESSIONID=50652D5AA72C4456866924BD7F6FDD72
Accept-Encoding: br,deflate,gzip,x-gzip

{
  "sellerId": 2,
  "title": "Skoda Fabia",
  "description": "Really cool fast car",
  "locationId": 1,
  "price": 25000,
  "phoneNumbers": [
    "123454321",
    "556677889"
  ],
  "vin": "1HGCM82633A000098",
  "make": "Skoda",
  "model": "Fabia",
  "bodyType": "City Car",
  "color": "Gray",
  "fuelType": "Petrol",
  "transmissionType": "Manual",
  "drivetrainType": "Front-Wheel Drive",
  "doorsCount": 4,
  "seatsCount": 5,
  "productionYear": 2010,
  "mileage": 51000,
  "enginePower": 71,
  "engineCapacity": 1198,
  "isDamaged": false,
  "features": [
    "Air Conditioning",
    "Power Windows"
  ]
}

###

POST http://localhost:8080/api/v1/adverts
Content-Type: application/json
Content-Length: 610
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.9)
Cookie: JSESSIONID=50652D5AA72C4456866924BD7F6FDD72
Accept-Encoding: br,deflate,gzip,x-gzip

{
  "sellerId": 2,
  "title": "Skoda Fabia",
  "description": "Really cool fast car",
  "locationId": 1,
  "price": 25000,
  "phoneNumbers": [
    "123454321",
    "556677889"
  ],
  "vin": "1HGCM82633A000098",
  "make": "Skoda",
  "model": "Fabia",
  "bodyType": "City Car",
  "color": "Gray",
  "fuelType": "Petrol",
  "transmissionType": "Manual",
  "drivetrainType": "Front-Wheel Drive",
  "doorsCount": 4,
  "seatsCount": 5,
  "productionYear": 2010,
  "mileage": 51000,
  "enginePower": 71,
  "engineCapacity": 1198,
  "isDamaged": false,
  "features": [
    "Air Conditioning",
    "Power Windows"
  ]
}

###

POST http://localhost:8080/api/v1/adverts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJURVNUIiwiaWF0IjoxNzEwNjg5NTIwLCJleHAiOjE3MTA3NzU5MjB9.byvMd_dT6Yex-w4ZxN12C2OWY7Lkj6DaYdBV8KJ10umZjPdeout7LxWbdRr6Ja1-hEeB5G2adTYW1c5DhD35Cw
Content-Length: 610
Connection: Keep-Alive
User-Agent: Apache-HttpClient/4.5.14 (Java/17.0.9)
Cookie: JSESSIONID=F78FB4AC00E9AEB5C385D59A96DED0EB
Accept-Encoding: br,deflate,gzip,x-gzip

{
  "sellerId": 2,
  "title": "Skoda Fabia",
  "description": "Really cool fast car",
  "locationId": 1,
  "price": 25000,
  "phoneNumbers": [
    "123454321",
    "556677889"
  ],
  "vin": "1HGCM82633A000098",
  "make": "Skoda",
  "model": "Fabia",
  "bodyType": "City Car",
  "color": "Gray",
  "fuelType": "Petrol",
  "transmissionType": "Manual",
  "drivetrainType": "Front-Wheel Drive",
  "doorsCount": 4,
  "seatsCount": 5,
  "productionYear": 2010,
  "mileage": 51000,
  "enginePower": 71,
  "engineCapacity": 1198,
  "isDamaged": false,
  "features": [
    "Air Conditioning",
    "Power Windows"
  ]
}

###

