DELETE localhost:8080/api/v1/image-collections/5/images
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJURVNUIiwiaWF0IjoxNzExMjkxOTc3LCJleHAiOjE3MTEzMDIwNTd9.sV2cATscg-GCm71bLai-virjt27xDasS_1dfjI8OrmY

{
  "imageUrls": [
    "https://iili.io/Jhkg4wv.jpg"
  ]
}